### ISSUE TITLE
Suggestion on initializing the composer autoloader

### ISSUE THREAD

**Issue by Vinai** [ikonoshirt/TopologicalSearch#1]
How about adding this to the top of `src/app/code/local/Mage/Sales/Model/Config/Ordered.php`:

```php
require_once BP . '/vendor/autoload.php';
```

I think it should be safe, but I'm not 100% confident...

The benefit adding the line provides is that it removes the requirement to manually edit some file during installation.

**Comment by Schrank** [comment]
try and error 🤷
